-- SQL이란 ?
-- DBMS에게 질의하는 명령어, 중복을 없애는 방법으로 결함을 줄임

--DDL(create/alter/drop)
--DML(select/insert/update/delete)
--DCL(grant/revoke)

INSERT INTO MEMBER_NEWLEC(ID, PWD) VALUES('newlec','111');
INSERT INTO MEMBER_NEWLEC(ID, PWD) VALUES('dragon','111');
INSERT INTO MEMBER_NEWLEC(ID, PWD) VALUES('test','111');
INSERT INTO MEMBER_NEWLEC (PWD,ID) VALUES('111','newlec');
COMMIT;
ROLLBACK;

SELECT * FROM MEMBER_NEWLEC;
SELECT ID "USER ID", NAME, PWD FROM MEMBER_NEWLEC mn ;

UPDATE MEMBER_NEWLEC SET PWD='222', NAME='손오공' WHERE ID='dragon' ;
DELETE MEMBER_NEWLEC WHERE ID='test';

-- 트랜잭션이란? 업무 실행단위 / 논리 명령단위 / 개념상의	--> commit , rollback 

SELECT HIT+1 FROM NOTICE_NEWLEC nn ;
SELECT HIT+1 AS HIT FROM notice;

SELECT 1+'3' FROM dual;
SELECT 1||'3' FROM dual;

SELECT * FROM MEMBER_NEWLEC mn ;
SELECT NAME||'('||ID||')' AS name FROM MEMBER_NEWLEC mn ;

SELECT * FROM MEMBER_NEWLEC mn ;
SELECT * FROM NOTICE_NEWLEC ;
SELECT * FROM NOTICE_NEWLEC WHERE WRITER_ID ='newlec';
SELECT * FROM NOTICE_NEWLEC WHERE HIT >3;
SELECT * FROM NOTICE_NEWLEC WHERE CONTENT IS NULL;

SELECT * FROM NOTICE_NEWLEC WHERE HIT =1 OR HIT =0 OR HIT =2;
SELECT * FROM NOTICE_NEWLEC WHERE 0<= HIT AND HIT <=2;
SELECT * FROM NOTICE_NEWLEC WHERE HIT BETWEEN 0 AND 2;
SELECT * FROM NOTICE_NEWLEC WHERE HIT IN (0,2,7);

-- 회원 중에서 박씨 성을 조회하라



INSERT INTO NOTICE_NEWLEC(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT, FILES) 
VALUES('5','Service 계층 추가하기', 'good', 'ggg', sysdate, 23,'');
SELECT * FROM NOTICE_NEWLEC WHERE TITLE LIKE 'J%'; 

SELECT * FROM MEMBER_NEWLEC WHERE NAME LIKE '박_';

SELECT * FROM MEMBER_NEWLEC WHERE NAME NOT LIKE '박_';
SELECT * FROM MEMBER_NEWLEC WHERE NAME LIKE '%도%';
SELECT * FROM NOTICE_NEWLEC WHERE TITLE LIKE '%DB%'; 
















