-- 숫자 함수
SELECT ABS(35),ABS(-35) FROM DUAL;
SELECT SIGN(35), SIGN(-35), SIGN(0) FROM DUAL;
SELECT ROUND(34.456789,2), ROUND(34.56789,3) FROM DUAL;
SELECT TRUNC(17/5) 몫, MOD(17,5) 나머지 FROM DUAL;
SELECT POWER(5,2), SQRT(25) FROM DUAL;

-- 날짜 함수
SELECT 
	SYSDATE
	, CURRENT_DATE
	, SYSTIMESTAMP
	, CURRENT_TIMESTAMP 
FROM DUAL;

ALTER SESSION SET TIME_ZONE='09:00';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT EXTRACT(MONTH FROM SYSDATE)||'월' FROM DUAL;

SELECT * FROM MEMBER_NEWLEC mn ;

SELECT * FROM MEMBER_NEWLEC mn WHERE ADD_MONTHS(SYSDATE,-6)<REGDATE;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2013-12-25')) FROM DUAL; 

SELECT SYSDATE FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'월') FROM DUAL;
 