-- 변환 함수
SELECT TO_CHAR(12345678,'$99,999,999,999.99') FROM DUAL;
SELECT 
	TRIM(TO_CHAR(1234567,'9,999,999'))||'원'
	,TO_CHAR(1234567.34567,'9,999,999.99')||'원' 
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD PM HH24:MI:SS'),SYSDATE FROM DUAL;
SELECT TO_DATE('2014-03-31 12:23:03','YYYY/MM/DD HH:MI:SS') FROM DUAL;
SELECT TO_NUMBER('1994') FROM DUAL;

-- NULL 관련 함수
SELECT NULL+3 FROM DUAL;
SELECT NVL(AGE,0) FROM MEMBER_NEWLEC mn ;
SELECT * FROM MEMBER_NEWLEC mn ;
SELECT TRUNC(AGE/10)*10 FROM MEMBER_NEWLEC mn ;

SELECT NVL2(AGE,TRUNC(AGE/10)*10,0) FROM MEMBER_NEWLEC mn ;

SELECT NULLIF(AGE,35) FROM MEMBER_NEWLEC mn ;

SELECT DECODE(GENDER,'남성',1,2) FROM MEMBER_NEWLEC mn ;


--SELECT 구절
-- SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY 순서까지 주의
--ORDER BY ASC, DESC
SELECT * FROM MEMBER_NEWLEC ORDER BY NAME ASC;
--아무것도 쓰지 않으면 오름차순 (ASC)

SELECT * FROM MEMBER_NEWLEC WHERE NAME LIKE '박%' ORDER BY AGE ASC;

SELECT * FROM NOTICE ORDER BY HIT DESC, REGDATE DESC;

-- 집계 함수와 GROUP BY
--SUM, MIN, MAX, COUNT, AVG
SELECT
	WRITER_ID
	, COUNT(ID) COUNT 
FROM NOTICE_NEWLEC 
GROUP BY WRITER_ID 
ORDER BY COUNT DESC;

SELECT * FROM NOTICE_NEWLEC ;

SELECT SUM(HIT) FROM NOTICE_NEWLEC nn ;
SELECT AVG(HIT) FROM NOTICE_NEWLEC nn ;

INSERT INTO NOTICE_NEWLEC (ID, REGDATE, HIT, WRITER_ID) VALUES(8, SYSDATE, 3, 'newlec');
--FROM -> CONNECT BY -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY
--순서대로 실행이 된다.



