-- ###정규식###

SELECT * FROM NOTICE_NEWLEC nn ;
SELECT * FROM NOTICE_NEWLEC WHERE REGEXP_LIKE(TITLE,'01[016-9]-\d{3,4}-\d{4}');
--010-2222-3333
--011-333-4444
--016-234-4353
--017-444-5555
--018-123-2345
--019-232-2345
^01[016-9]-\d{3,4}-\d{4}$

--[0-9a-zA-Z] = \w
--* => 0개 이상
--+ => 1개 이상
--\D\w*@\Dw*.[org|net|com]
SELECT * FROM NOTICE_NEWLEC;
SELECT * FROM MEMBER_NEWLEC mn ;


SELECT ROWNUM,N.* FROM MEMBER_NEWLEC N;

ALTER TABLE MEMBER_NEWLEC ADD EMAIL VARCHAR2(200);

SELECT * FROM NOTICE_NEWLEC ;
SELECT ROWNUM,N.* FROM NOTICE_NEWLEC N WHERE ROWNUM BETWEEN 1 AND 5;
-- ROWNUM이 기준으로 들어가기 때문에 중간부터인 6-7이런식으로는 불가능하다.

SELECT * FROM (SELECT ROWNUM AS NUM, M.* FROM NOTICE_NEWLEC M) 
WHERE NUM BETWEEN 6 AND 10;

SELECT * FROM MEMBER_NEWLEC;


INSERT INTO NOTICE_NEWLEC(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT, FILES)
VALUES('7','선반-접시-그릇 이 세가지요~~', 'okay', '연락처를 남깁니다.', sysdate, 23,'');

UPDATE MEMBER_NEWLEC SET NAME = '뉴렉', AGE = 35 WHERE ID = 'newlec';

INSERT INTO MEMBER_NEWLEC(ID, PWD, NAME, AGE)
VALUES('kang', 111, '강호동', 35);


SELECT DISTINCT age FROM MEMBER_NEWLEC mn ;

SELECT LENGTH('HELLO') FROM DUAL;
--DML (CRUD)
